Análise da Dados

In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [48]:
negociaçoes = r"C:\Users\Orçamento\OneDrive - GRUPO RETEC\02. Engenharia\Dep. Orçamentos\POWERBI\AUTOMAÇÃO RD\negociacoes_2025.xlsx"
df = pd.read_excel(negociaçoes)

In [49]:
print(df.head)

<bound method NDFrame.head of                            _id                        id  \
0     681a49b3063c96001423f094  681a49b3063c96001423f094
1     681a49a40420020018b1809f  681a49a40420020018b1809f
2     681a2939a696a7001a149ebc  681a2939a696a7001a149ebc
3     681a0788845e92001cbaddc2  681a0788845e92001cbaddc2
4     681a0546ab3bde0027bb35f0  681a0546ab3bde0027bb35f0
...                        ...                       ...
2781  677685aac7ad66001f69dbc5  677685aac7ad66001f69dbc5
2782  6776855e2d52460014191210  6776855e2d52460014191210
2783  6776855279d2c00017fdea61  6776855279d2c00017fdea61
2784  677679be82e94600174715a2  677679be82e94600174715a2
2785  677676ac2d5246001818fd9d  677676ac2d5246001818fd9d

                                                   name  amount_montly  \
0                       P.V 13970 JJ COIFAS OBRA: COIFA              0
1                       P.V 13970 JJ COIFAS OBRA: COIFA              0
2                            12253 - TEUTO - ENG. JULIP              0
3     NCP 12244 - BACCIO DI LATTE  - ARCOBRAS COMEERCIO              0
4                  NCP-12220 NEW YORK OBRA: RESIDENCIAL              0
...                                                 ...            ...
2781                          PV 12544 - EDUARDO FABBRO              0
2782                 PV 12542 - LAVANDERIA PATRICK BEAL              0
2783                 PV 12542 - LAVANDERIA PATRICK BEAL              0
2784  NCP 10317 - CASA VARANDA - ISRAEL GRADO ENGENH...              0
2785  NCP 10317 - CASA VARANDA - ISRAEL GRADO ENGENH...              0

      amount_unique  amount_total prediction_date  markup last_activity_at  \
0              0.00          0.00             NaN  future              NaN
1             41.94         41.94             NaN  future              NaN
2              0.00          0.00             NaN  future              NaN
3              0.00          0.00             NaN  future              NaN
4            710.52        710.52             NaN  future              NaN
...             ...           ...             ...     ...              ...
2781         160.99        160.99             NaN  future              NaN
2782           0.00          0.00             NaN  future              NaN
2783         201.63        201.63             NaN  future              NaN
2784           0.00          0.00             NaN  future              NaN
2785         308.32        308.32             NaN  future              NaN

      interactions  ... deal_lost_reason._id deal_lost_reason.id  \
0                0  ...                  NaN                 NaN
1                1  ...                  NaN                 NaN
2                2  ...                  NaN                 NaN
3                0  ...                  NaN                 NaN
4                0  ...                  NaN                 NaN
...            ...  ...                  ...                 ...
2781             1  ...                  NaN                 NaN
2782             0  ...                  NaN                 NaN
2783             1  ...                  NaN                 NaN
2784             0  ...                  NaN                 NaN
2785             1  ...                  NaN                 NaN

     deal_lost_reason.name  deal_lost_reason.created_at  \
0                      NaN                          NaN
1                      NaN                          NaN
2                      NaN                          NaN
3                      NaN                          NaN
4                      NaN                          NaN
...                    ...                          ...
2781                   NaN                          NaN
2782                   NaN                          NaN
2783                   NaN                          NaN
2784                   NaN                          NaN
2785                   NaN                          NaN

     deal_lost_reason.updated_at campaign._id  campaign.id  campaign.name  \
0                            NaN          NaN          NaN            NaN
1                            NaN          NaN          NaN            NaN
2                            NaN          NaN          NaN            NaN
3                            NaN          NaN          NaN            NaN
4                            NaN          NaN          NaN            NaN
...                          ...          ...          ...            ...
2781                         NaN          NaN          NaN            NaN
2782                         NaN          NaN          NaN            NaN
2783                         NaN          NaN          NaN            NaN
2784                         NaN          NaN          NaN            NaN
2785                         NaN          NaN          NaN            NaN

      campaign.created_at campaign.updated_at
0                     NaN                 NaN
1                     NaN                 NaN
2                     NaN                 NaN
3                     NaN                 NaN
4                     NaN                 NaN
...                   ...                 ...
2781                  NaN                 NaN
2782                  NaN                 NaN
2783                  NaN                 NaN
2784                  NaN                 NaN
2785                  NaN                 NaN

[2786 rows x 69 columns]>

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2786 entries, 0 to 2785
Data columns (total 69 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   _id                                   2786 non-null   object
 1   id                                    2786 non-null   object
 2   name                                  2786 non-null   object
 3   amount_montly                         2786 non-null   int64
 4   amount_unique                         2786 non-null   float64
 5   amount_total                          2786 non-null   float64
 6   prediction_date                       3 non-null      object
 7   markup                                2786 non-null   object
 8   last_activity_at                      1 non-null      object
 9   interactions                          2786 non-null   int64
 10  markup_last_activities                1 non-null      object
 11  created_at                            2786 non-null   object
 12  updated_at                            2786 non-null   object
 13  rating                                2786 non-null   int64
 14  markup_created                        2786 non-null   object
 15  last_activity_content                 1 non-null      object
 16  user_changed                          2786 non-null   bool
 17  hold                                  0 non-null      float64
 18  win                                   1263 non-null   float64
 19  closed_at                             1263 non-null   object
 20  contacts                              2786 non-null   object
 21  deal_custom_fields                    2786 non-null   object
 22  deal_products                         2786 non-null   object
 23  organization._id                      2786 non-null   object
 24  organization.id                       2786 non-null   object
 25  organization.name                     2786 non-null   object
 26  organization.address                  1 non-null      object
 27  organization.address_latitude         1 non-null      float64
 28  organization.address_longitude        1 non-null      float64
 29  organization.user._id                 2786 non-null   object
 30  organization.user.id                  2786 non-null   object
 31  organization.user.name                2786 non-null   object
 32  organization.user.email               2786 non-null   object
 33  organization.organization_segments    2786 non-null   object
 34  user._id                              2786 non-null   object
 35  user.id                               2786 non-null   object
 36  user.name                             2786 non-null   object
 37  user.nickname                         2786 non-null   object
 38  user.email                            2786 non-null   object
 39  deal_stage._id                        2786 non-null   object
 40  deal_stage.id                         2786 non-null   object
 41  deal_stage.name                       2786 non-null   object
 42  deal_stage.nickname                   2786 non-null   object
 43  deal_stage.created_at                 2786 non-null   object
 44  deal_stage.updated_at                 2786 non-null   object
 45  stop_time_limit.expiration_date_time  288 non-null    object
 46  stop_time_limit.expired               288 non-null    float64
 47  stop_time_limit.expired_days          288 non-null    float64
 48  next_task._id                         49 non-null     object
 49  next_task.id                          49 non-null     object
 50  next_task.date                        49 non-null     object
 51  next_task.subject                     49 non-null     object
 52  next_task.type                        49 non-null     object
 53  next_task.hour                        49 non-null     object
 54  deal_source._id                       148 non-null    object
 55  deal_source.id                        148 non-null    object
 56  deal_source.name                      148 non-null    object
 57  deal_source.created_at                148 non-null    object
 58  deal_source.updated_at                148 non-null    object
 59  deal_lost_reason._id                  118 non-null    object
 60  deal_lost_reason.id                   118 non-null    object
 61  deal_lost_reason.name                 118 non-null    object
 62  deal_lost_reason.created_at           118 non-null    object
 63  deal_lost_reason.updated_at           118 non-null    object
 64  campaign._id                          3 non-null      object
 65  campaign.id                           3 non-null      object
 66  campaign.name                         3 non-null      object
 67  campaign.created_at                   3 non-null      object
 68  campaign.updated_at                   3 non-null      object
dtypes: bool(1), float64(8), int64(3), object(57)
memory usage: 1.4+ MB

In [51]:
df.describe()

,amount_montly,amount_unique,amount_total,interactions,rating,hold,win,organization.address_latitude,organization.address_longitude,stop_time_limit.expired,stop_time_limit.expired_days
count,2786.0,2.786000e+03,2.786000e+03,2786.000000,2786.000000,0.0,1263.000000,1.000000,1.000000,288.000000,288.000000
mean,0.0,3.876990e+04,3.876990e+04,1.364322,2.274228,NaN,0.906572,-16.708663,-49.235882,0.704861,26.958333
std,0.0,4.853574e+05,4.853574e+05,2.643322,1.829196,NaN,0.291147,NaN,NaN,0.456899,28.678046
min,0.0,0.000000e+00,0.000000e+00,0.000000,1.000000,NaN,0.000000,-16.708663,-49.235882,0.000000,0.000000
25%,0.0,0.000000e+00,0.000000e+00,0.000000,1.000000,NaN,1.000000,-16.708663,-49.235882,0.000000,0.000000
50%,0.0,1.454950e+02,1.454950e+02,1.000000,1.000000,NaN,1.000000,-16.708663,-49.235882,1.000000,13.000000
75%,0.0,2.114332e+03,2.114332e+03,1.000000,5.000000,NaN,1.000000,-16.708663,-49.235882,1.000000,46.000000
max,0.0,1.339870e+07,1.339870e+07,27.000000,5.000000,NaN,1.000000,-16.708663,-49.235882,1.000000,118.000000

In [52]:
df.columns

Index(['_id', 'id', 'name', 'amount_montly', 'amount_unique', 'amount_total',
       'prediction_date', 'markup', 'last_activity_at', 'interactions',
       'markup_last_activities', 'created_at', 'updated_at', 'rating',
       'markup_created', 'last_activity_content', 'user_changed', 'hold',
       'win', 'closed_at', 'contacts', 'deal_custom_fields', 'deal_products',
       'organization._id', 'organization.id', 'organization.name',
       'organization.address', 'organization.address_latitude',
       'organization.address_longitude', 'organization.user._id',
       'organization.user.id', 'organization.user.name',
       'organization.user.email', 'organization.organization_segments',
       'user._id', 'user.id', 'user.name', 'user.nickname', 'user.email',
       'deal_stage._id', 'deal_stage.id', 'deal_stage.name',
       'deal_stage.nickname', 'deal_stage.created_at', 'deal_stage.updated_at',
       'stop_time_limit.expiration_date_time', 'stop_time_limit.expired',
       'stop_time_limit.expired_days', 'next_task._id', 'next_task.id',
       'next_task.date', 'next_task.subject', 'next_task.type',
       'next_task.hour', 'deal_source._id', 'deal_source.id',
       'deal_source.name', 'deal_source.created_at', 'deal_source.updated_at',
       'deal_lost_reason._id', 'deal_lost_reason.id', 'deal_lost_reason.name',
       'deal_lost_reason.created_at', 'deal_lost_reason.updated_at',
       'campaign._id', 'campaign.id', 'campaign.name', 'campaign.created_at',
       'campaign.updated_at'],
      dtype='object')

Análise, criando o dataframe com as colunas que queremos analisar

In [53]:
colunas_corrigidas = [
    "id", "name", "amount_total", "amount_unique", "markup",
    "created_at", "closed_at", "last_activity_at",
    "interactions", "win", "deal_stage.name", "user.id", "user.name",
    "deal_lost_reason.name"
]

df_analise = df[colunas_corrigidas].copy()

Transformando a coluna de Datas em tipo data

In [65]:
df_analise['created_at'] = pd.to_datetime(df_analise['created_at'], errors = 'coerce')
df_analise['closed_at'] = pd.to_datetime(df_analise['closed_at'], errors = 'coerce')
df_analise["last_activity_at"] = pd.to_datetime(df_analise["last_activity_at"], errors="coerce")

In [66]:
df_analise.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2786 entries, 0 to 2785
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     2786 non-null   object
 1   name                   2786 non-null   object
 2   amount_total           2786 non-null   float64
 3   amount_unique          2786 non-null   float64
 4   markup                 2786 non-null   object
 5   created_at             2786 non-null   datetime64[ns, UTC-03:00]
 6   closed_at              1263 non-null   datetime64[ns, UTC-03:00]
 7   last_activity_at       1 non-null      datetime64[ns, UTC-03:00]
 8   interactions           2786 non-null   int64
 9   win                    1263 non-null   float64
 10  deal_stage.name        2786 non-null   object
 11  user.id                2786 non-null   object
 12  user.name              2786 non-null   object
 13  deal_lost_reason.name  118 non-null    object
dtypes: datetime64[ns, UTC-03:00](3), float64(3), int64(1), object(7)
memory usage: 304.8+ KB

In [64]:
df_analise.head()

,id,name,amount_total,amount_unique,markup,created_at,closed_at,last_activity_at,interactions,win,deal_stage.name,user.id,user.name,deal_lost_reason.name
0,681a49b3063c96001423f094,P.V 13970 JJ COIFAS OBRA: COIFA,0.00,0.00,future,2025-05-06 14:41:07.414000-03:00,NaT,NaN,0,NaN,Venda Ganha,651af77665445f0022476065,Wellisson Chaves,NaN
1,681a49a40420020018b1809f,P.V 13970 JJ COIFAS OBRA: COIFA,41.94,41.94,future,2025-05-06 14:40:52.625000-03:00,2025-05-06 14:41:07.261000-03:00,NaN,1,1.0,Venda Ganha,651af77665445f0022476065,Wellisson Chaves,NaN
2,681a2939a696a7001a149ebc,12253 - TEUTO - ENG. JULIP,0.00,0.00,future,2025-05-06 12:22:34.040000-03:00,NaT,NaN,2,NaN,Orç. Fazendo (Venda),65f878886cab6d0015e4690f,Iago Rangel,NaN
3,681a0788845e92001cbaddc2,NCP 12244 - BACCIO DI LATTE - ARCOBRAS COMEERCIO,0.00,0.00,future,2025-05-06 09:58:49.161000-03:00,NaT,NaN,0,NaN,Orç. Pendente (Concorrência),651af6998076130019a8dda8,Luan Araújo,NaN
4,681a0546ab3bde0027bb35f0,NCP-12220 NEW YORK OBRA: RESIDENCIAL,710.52,710.52,future,2025-05-06 09:49:10.630000-03:00,NaT,NaN,0,NaN,Venda Ganha,651af77665445f0022476065,Wellisson Chaves,NaN

In [67]:
# Converter campo win em booleano
df_analise["win"] = df_analise["win"].map({"true": True, "false": False})

# Recriar colunas auxiliares
df_analise["duracao_venda_dias"] = (df_analise["closed_at"] - df_analise["created_at"]).dt.days
df_analise["mes_criacao"] = df_analise["created_at"].dt.to_period("M")
df_analise["status_final"] = df_analise["win"].map({True: "Ganho", False: "Perdido"})
df_analise.loc[df_analise["closed_at"].isna(), "status_final"] = "Em Aberto"

C:\Users\Orçamento\AppData\Local\Temp\ipykernel_33444\307753490.py:6: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df_analise["mes_criacao"] = df_analise["created_at"].dt.to_period("M")

In [70]:
df_analise[::-10]

,id,name,amount_total,amount_unique,markup,created_at,closed_at,last_activity_at,interactions,win,deal_stage.name,user.id,user.name,deal_lost_reason.name,duracao_venda_dias,mes_criacao,status_final
2785,677676ac2d5246001818fd9d,NCP 10317 - CASA VARANDA - ISRAEL GRADO ENGENH...,308.32,308.32,future,2025-01-02 08:21:16.306000-03:00,2024-12-31 01:00:00-03:00,NaT,1,NaN,Venda Ganha,651af6998076130019a8dda8,Luan Araújo,NaN,-3.0,2025-01,NaN
2775,6776c1f3d65038001edb2955,8098 - GEOLAB - GLEICIANE,28092.88,28092.88,future,2025-01-02 13:42:27.410000-03:00,NaT,NaT,1,NaN,Negociação,651af40601a5360011f74f6c,Rutemar Júnior,NaN,NaN,2025-01,Em Aberto
2765,6777c299d650380018db8bed,NCP 10326 - SARAH LAGO NORTE - JICLIMAR REFRIG...,0.00,0.00,future,2025-01-03 07:57:29.274000-03:00,NaT,NaT,0,NaN,Venda Ganha,651af6998076130019a8dda8,Luan Araújo,NaN,NaN,2025-01,Em Aberto
2755,6777ea816fbbb3001b6e5a94,NCP 10315 - FUNCEF - ALTRI CONSTRUTORA,8648.41,8648.41,future,2025-01-03 10:47:46.014000-03:00,2025-02-03 15:21:02.397000-03:00,NaT,11,NaN,Venda Perdida,651af6998076130019a8dda8,Luan Araújo,Relacionamento (Confiança e Parceria),31.0,2025-01,NaN
2745,6778280080810e001f34511d,NCP 10313 - CIVIL EMG - ARAUJO ABREU ENGENHARIA,1007.19,1007.19,future,2025-01-03 15:10:08.890000-03:00,2025-01-03 15:59:55.427000-03:00,NaT,1,NaN,Venda Ganha,651af6998076130019a8dda8,Luan Araújo,NaN,0.0,2025-01,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,6812d77c2e0f3b00142a1b7b,12149 - BOATE SOHO - PAULO,0.00,0.00,future,2025-04-30 23:07:56.441000-03:00,NaT,NaT,0,NaN,Venda Ganha,65f878886cab6d0015e4690f,Iago Rangel,NaN,NaN,2025-04,Em Aberto
35,6815143c503cb3001431484b,NCP- 12208 MONTE SIAO OBRA: RESTAURANTE,825.53,825.53,future,2025-05-02 15:51:40.718000-03:00,2025-05-02 15:52:00.255000-03:00,NaT,3,NaN,Venda Ganha,651af77665445f0022476065,Wellisson Chaves,NaN,0.0,2025-05,NaN
25,6817d7e69bf42000143ae859,NCT-X 8065-25 - JOULE - HOSPITAL ANIS RASSI - ...,478361.31,478361.31,future,2025-05-04 18:11:03.022000-03:00,NaT,NaT,1,NaN,Negociação,651af445559e310016d78cfb,Gabriel Bento,NaN,NaN,2025-05,Em Aberto
15,6818b701d84e620014918d87,NCP-12126 CONDOMINIO DO CENTRO OBRA: CNC,0.00,0.00,future,2025-05-05 10:02:57.341000-03:00,NaT,NaT,0,NaN,Venda Ganha,651af77665445f0022476065,Wellisson Chaves,NaN,NaN,2025-05,Em Aberto
5,6819101f1573cb001d59fbea,NCP - 12247 SANTA CATARINA TRIBUNAL DE JUSTIÇA,12127.80,12127.80,future,2025-05-05 16:23:11.790000-03:00,NaT,NaT,2,NaN,Negociação,655ca6a9d691d60021c81701,Marlon Souza,NaN,NaN,2025-05,Em Aberto

Estatísticas principais

In [100]:
resumo = {
    "Total de negociações": len(df_analise),
    "Contagem de Vendas Ganhas" : df_analise[df_analise["deal_stage.name"] == "Venda Ganha"].shape[0],
    "Contagem de Vendas Perdidas" : df_analise[df_analise["deal_stage.name"] == "Venda Perdida"].shape[0],
    "Contagem de Vendas Canceladas" : df_analise[df_analise["deal_stage.name"] == "Venda Cancelada"].shape[0],
    "Contagem de Vendas em aberto" : df_analise[df_analise["deal_stage.name"] == "Negociação"].shape[0],
    "Valor Total Ganhas": float(df_analise[df_analise["deal_stage.name"] == "Venda Ganha"]["amount_total"].sum()),
    "Valor Total Perdidas": float(df_analise[df_analise["deal_stage.name"] == "Venda Perdida"]["amount_total"].sum()),
    "Valor Total Canceladas": float(df_analise[df_analise["deal_stage.name"] == "Venda Cancelada"]["amount_total"].sum()),
    "Valor Total Não vendas": float(df_analise[df_analise["deal_stage.name"].isin(["Venda Perdida", "Venda Cancelada"])]["amount_total"].sum()),
    "Valor Total em Aberto": float(df_analise[df_analise["deal_stage.name"] == "Negociação"]["amount_total"].sum()),
    "Valor Total Ganho": df_analise[df_analise["status_final"] == "Ganho"]["amount_total"].sum(),
    "Ticket Médio Ganho": df_analise[df_analise["status_final"] == "Ganho"]["amount_total"].mean(),
    "Duração média (dias)": df_analise["duracao_venda_dias"].mean()
}

In [101]:
resumo

{'Total de negociações': 2786,
 'Contagem de Vendas Ganhas': 2316,
 'Contagem de Vendas Perdidas': 90,
 'Contagem de Vendas Canceladas': 27,
 'Contagem de Vendas em aberto': 123,
 'Valor Total Ganhas': 6215609.68,
 'Valor Total Perdidas': 3061888.3100000005,
 'Valor Total Canceladas': 1106928.4,
 'Valor Total Não vendas': 4168816.71,
 'Valor Total em Aberto': 10039137.240000002,
 'Valor Total Ganho': np.float64(0.0),
 'Ticket Médio Ganho': nan,
 'Duração média (dias)': np.float64(3.5566112430720507)}